resources:
- namespace.yaml
- postgres/pvc.yaml
- postgres/pv-postgres.yaml
- postgres/deployment.yaml
- postgres/service.yaml
- zabbix-server/deployment.yaml
- zabbix-server/service.yaml
- zabbix-web/deployment.yaml

- zabbix-web/service.yaml
