apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zabbix-postgres
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.203
    path: /srv/k8s-nfs/zabbix-postgres
